apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: [base64-encoded-password]
  MYSQL_DATABASE: [base64-encoded-database-name]
  MYSQL_USER: [base64-encoded-user]
  MYSQL_PASSWORD: [base64-encoded-user-password]
